version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:00"
      timezone: "Africa/Cairo"
    open-pull-requests-limit: 10
    groups:
       dev-dependencies:
          applies-to: version-updates
          patterns:
            - "*"
    
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:00"
      timezone: "Africa/Cairo"
    open-pull-requests-limit: 10