version: 2
updates:
  - package-ecosystem: "maven"
    directories:
      - "/GUI_Web"
      - "/GUI_Web_Basic"
      - "/GUI_Web_Cucumber"
    schedule:
      interval: "daily"
    groups:
      dev:
        applies-to: version-updates
    target-branch: main

    
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: main
